In [13]:
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt

In [14]:
def neglect_terms(expr, N):
    # Function to neglect terms of order N and higher in a polynomial
    # Split the expression into numerator and denominator
    num, denom = expr.as_numer_denom()
    # Process numerator and denominator to remove terms of order N and higher
    num_neglected = sum(coeff * term for term, coeff in num.as_coefficients_dict().items() if all(pow < N for var, pow in term.as_powers_dict().items()))
    denom_neglected = sum(coeff * term for term, coeff in denom.as_coefficients_dict().items() if all(pow < N for var, pow in term.as_powers_dict().items()))
    # Reconstruct the fraction
    return num_neglected / denom_neglected

def neglect_terms_in_matrix(matrix, N):
    # Process each element in the matrix
    processed_matrix = matrix.applyfunc(lambda x: neglect_terms(x, N))

    return processed_matrix

In [51]:
# Define the symbols
alpha= sym.symbols('\\alpha', real=True, positive = True, nonzero=True)
N=6
C_mat = sym.Matrix(N,N, lambda i, j: -alpha if abs(i-j) == 1 else 1+alpha if i==j else 0)
I = sym.Matrix(N,N, lambda i, j:  1 if i==j else 0)

In [52]:
C_mat

Matrix([
[\alpha + 1,    -\alpha,          0,          0,          0,          0],
[   -\alpha, \alpha + 1,    -\alpha,          0,          0,          0],
[         0,    -\alpha, \alpha + 1,    -\alpha,          0,          0],
[         0,          0,    -\alpha, \alpha + 1,    -\alpha,          0],
[         0,          0,          0,    -\alpha, \alpha + 1,    -\alpha],
[         0,          0,          0,          0,    -\alpha, \alpha + 1]])

In [19]:
C_inv = C_mat**-1
C_inv

Matrix([
[      (-4*\alpha**4 - 2*\alpha**3 + 6*\alpha**2 + 5*\alpha + 1)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1),     (-\alpha**5 - 2*\alpha**4 + 3*\alpha**3 + 4*\alpha**2 + \alpha)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1),      (-\alpha**5 + \alpha**4 + 3*\alpha**3 + \alpha**2)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1),                               (2*\alpha**4 + \alpha**3)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1),                                             (\alpha**5 + \alpha**4)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1),                                                       \alpha**5/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1)],
[(-\alpha**5 - 2*\alpha**4 + 3*\alpha**3 + 4*\alpha**2 + \alpha)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1), (-\alpha**5 - 3*\alpha**4 + \alpha**3 + 7*\alpha**2

In [20]:
C_inv_neglect = neglect_terms_in_matrix(C_inv,2)
C_inv_neglect

Matrix([
[(5*\alpha + 1)/(6*\alpha + 1),         \alpha/(6*\alpha + 1),                             0,                             0,                             0,                             0],
[        \alpha/(6*\alpha + 1), (5*\alpha + 1)/(6*\alpha + 1),         \alpha/(6*\alpha + 1),                             0,                             0,                             0],
[                            0,         \alpha/(6*\alpha + 1), (5*\alpha + 1)/(6*\alpha + 1),         \alpha/(6*\alpha + 1),                             0,                             0],
[                            0,                             0,         \alpha/(6*\alpha + 1), (5*\alpha + 1)/(6*\alpha + 1),         \alpha/(6*\alpha + 1),                             0],
[                            0,                             0,                             0,         \alpha/(6*\alpha + 1), (5*\alpha + 1)/(6*\alpha + 1),         \alpha/(6*\alpha + 1)],
[                            0,                    

In [21]:
C_inv_approx = sum( [(I-C_mat)**n for n in range(2)],  sym.zeros(N))

In [22]:
C_inv_approx

Matrix([
[1 - \alpha,     \alpha,          0,          0,          0,          0],
[    \alpha, 1 - \alpha,     \alpha,          0,          0,          0],
[         0,     \alpha, 1 - \alpha,     \alpha,          0,          0],
[         0,          0,     \alpha, 1 - \alpha,     \alpha,          0],
[         0,          0,          0,     \alpha, 1 - \alpha,     \alpha],
[         0,          0,          0,          0,     \alpha, 1 - \alpha]])

In [42]:
C_R

7.5

In [65]:
C=15
CJ=3
Csh=15
Cc = 1
C_R = C / 2
C_C = Cc
C_F = C / 2 + Csh + CJ
C_F = C / 2 + Cc

C_mat = np.array([[C_R + C_C / 2, 0             , -C_C / 2      , -C_C / 2      , 0             ,        0      ],
                  [0            , C_F + C_C / 2 , -C_C / 2      , -C_C / 2      , 0             , 0             ],
                  [-C_C / 2     , -C_C / 2      , C_R + C_C / 2 , 0             , -C_C / 2      , -C_C / 2      ],
                  [-C_C / 2     , -C_C / 2      , 0             , C_F + C_C / 2 , -C_C / 2      , -C_C / 2      ],
                  [0            , 0             , -C_C / 2      , -C_C / 2      , C_R + C_C / 2 , 0             ],
                  [0            , 0             , -C_C / 2      , -C_C / 2      , 0             , C_F + C_C / 2 ]])

C_inv_a = (1/C_R)**2 * np.array([   [C_R  - C_C / 2, 0           , C_C / 2      , C_C / 2      , 0             ,        0      ],
                                    [0              , C_F - C_C / 2 , C_C / 2      , C_C / 2      , 0             , 0             ],
                                    [C_C / 2        , C_C / 2      , C_R  - C_C / 2 , 0             , C_C / 2      , C_C / 2      ],
                                    [C_C / 2        , C_C / 2      , 0             , C_F - C_C / 2 , C_C / 2      , C_C / 2      ],
                                    [0            , 0             , C_C / 2      , C_C / 2      , C_R  - C_C / 2 , 0             ],
                                    [0            , 0             , C_C / 2      , C_C / 2      , 0             , C_F - C_C / 2 ]])
C_mat

array([[ 8. ,  0. , -0.5, -0.5,  0. ,  0. ],
       [ 0. ,  9. , -0.5, -0.5,  0. ,  0. ],
       [-0.5, -0.5,  8. ,  0. , -0.5, -0.5],
       [-0.5, -0.5,  0. ,  9. , -0.5, -0.5],
       [ 0. ,  0. , -0.5, -0.5,  8. ,  0. ],
       [ 0. ,  0. , -0.5, -0.5,  0. ,  9. ]])

In [66]:
np.linalg.inv(C_mat)

array([[0.12594875, 0.00084334, 0.00803651, 0.00714357, 0.00094875,
        0.00084334],
       [0.00084334, 0.11186074, 0.00714357, 0.00634984, 0.00084334,
        0.00074963],
       [0.00803651, 0.00714357, 0.12689751, 0.00168668, 0.00803651,
        0.00714357],
       [0.00714357, 0.00634984, 0.00168668, 0.11261038, 0.00714357,
        0.00634984],
       [0.00094875, 0.00084334, 0.00803651, 0.00714357, 0.12594875,
        0.00084334],
       [0.00084334, 0.00074963, 0.00714357, 0.00634984, 0.00084334,
        0.11186074]])

In [67]:
C_inv_a

array([[0.12444444, 0.        , 0.00888889, 0.00888889, 0.        ,
        0.        ],
       [0.        , 0.14222222, 0.00888889, 0.00888889, 0.        ,
        0.        ],
       [0.00888889, 0.00888889, 0.12444444, 0.        , 0.00888889,
        0.00888889],
       [0.00888889, 0.00888889, 0.        , 0.14222222, 0.00888889,
        0.00888889],
       [0.        , 0.        , 0.00888889, 0.00888889, 0.12444444,
        0.        ],
       [0.        , 0.        , 0.00888889, 0.00888889, 0.        ,
        0.14222222]])

In [47]:
B = sym.Matrix(N,N, lambda i, j: -1 if abs(i-j) == 1 else 0)

In [48]:
B 

Matrix([
[ 0, -1,  0,  0,  0,  0],
[-1,  0, -1,  0,  0,  0],
[ 0, -1,  0, -1,  0,  0],
[ 0,  0, -1,  0, -1,  0],
[ 0,  0,  0, -1,  0, -1],
[ 0,  0,  0,  0, -1,  0]])

In [53]:
C_mat

Matrix([
[\alpha + 1,    -\alpha,          0,          0,          0,          0],
[   -\alpha, \alpha + 1,    -\alpha,          0,          0,          0],
[         0,    -\alpha, \alpha + 1,    -\alpha,          0,          0],
[         0,          0,    -\alpha, \alpha + 1,    -\alpha,          0],
[         0,          0,          0,    -\alpha, \alpha + 1,    -\alpha],
[         0,          0,          0,          0,    -\alpha, \alpha + 1]])

In [54]:
B * C_inv_approx* B

Matrix([
[1 - \alpha,     2*\alpha,   1 - \alpha,       \alpha,            0,          0],
[  2*\alpha, 2 - 2*\alpha,     3*\alpha,   1 - \alpha,       \alpha,          0],
[1 - \alpha,     3*\alpha, 2 - 2*\alpha,     3*\alpha,   1 - \alpha,     \alpha],
[    \alpha,   1 - \alpha,     3*\alpha, 2 - 2*\alpha,     3*\alpha, 1 - \alpha],
[         0,       \alpha,   1 - \alpha,     3*\alpha, 2 - 2*\alpha,   2*\alpha],
[         0,            0,       \alpha,   1 - \alpha,     2*\alpha, 1 - \alpha]])