In [1]:
import Modules.SQcircuit_extensions as sq_ext
import numpy as np
from importlib import reload
reload(sq_ext)


<module 'Modules.SQcircuit_extensions' from 'C:\\Users\\gabri\\PycharmProjects\\tunable-capacitive-coupling-flux-qubits\\Modules\\SQcircuit_extensions.py'>

<Figure size 640x480 with 0 Axes>

In [2]:
nH = 1e-9
fF = 1e-15
GHz = 1e9
h = 6.626e-34
e0 = 1.602e-19
Φ_0 = h / (2 * e0)

In [7]:
CR, CF, LF, LR, EJ, Δ, ω_r = sq_ext.get_experimental_parameters('qubit_1', return_effective=True)
φ_ext =0.5

In [8]:
fluxonium_res = sq_ext.sq_fluxonium(C_F_eff=CF, L_F_eff=LF, EJ=0)
fluxonium = sq_ext.sq_fluxonium(C_F_eff=CF, L_F_eff=LF, EJ=EJ, φ_ext=φ_ext)

fluxonium.hamiltonian()

Φ_res = fluxonium.flux_op(0)
Q_res = fluxonium.charge_op(0)
cos   = fluxonium.cos_op(0)
sin   = fluxonium.sin_op(0)

CF_su = CF * fF
LF_su = LF * nH
EJ_su = EJ * GHz 

H_fluxonium_res = Q_res ** 2 / CF_su / 2 + Φ_res ** 2 / LF_su / 2
H_fluxonium     = H_fluxonium_res - EJ_su * 2 * np.pi  * (cos * np.cos(2 * np.pi * φ_ext) + sin * np.sin(2 * np.pi * φ_ext) )

In [9]:
sq_ext.diag(H_fluxonium_res, 4, remove_ground=True)[0], sq_ext.diag(fluxonium_res.hamiltonian(), 4, remove_ground=True)[0]

(array([ 0.       ,  5.9762243, 11.9524486, 17.9286729]),
 array([ 0.       ,  5.9762243, 11.9524486, 17.9286729]))

In [10]:
sq_ext.diag(H_fluxonium, 4, remove_ground=True)[0][1:],  sq_ext.diag(fluxonium.hamiltonian(), 4, remove_ground=True)[0][1:]

(array([ 3.68869788,  8.09475116, 12.92585805]),
 array([ 3.68869788,  8.09475116, 12.92585805]))