In [21]:
import Modules.SQcircuit_extensions as sq_ext
import Modules.figures as figs
import SQcircuit as sq
import numpy as np
import matplotlib.pyplot as plt
import importlib
import qutip as qt
import scipy as sp
%matplotlib ipympl

plt.rcParams['text.usetex'] = False
importlib.reload(sq_ext)
importlib.reload(sq)
importlib.reload(figs)
np.set_printoptions(linewidth=200, formatter={'float': '{:.6f}'.format})
# np.set_printoptions(linewidth=200, formatter={'float': '{:.3e}'.format})

In [22]:
GHz=1e9

In [23]:
def premade_coupled_resonators(Δ):
    if Δ == 0:
        C   = sq.Capacitor(1, 'fF')
        L   = sq.Inductor(1, 'nH')
        elements = {(0, 1): [L, C],
                    (0, 2): [L, C], }
        return sq.Circuit(elements)

    else:
        C = sq.Capacitor(1, 'fF')
        L = sq.Inductor(1, 'nH')
        L_Δ = sq.Inductor(Δ, 'nH')
        elements = {(0, 1): [L, C],
                    (0, 2): [L, C],
                    (1, 2): [L_Δ], }
        return sq.Circuit(elements)

def premade_single_resonator(Δ):
    if Δ == 0:
        C   = sq.Capacitor(1, 'fF')
        L   = sq.Inductor(1,  'nH')
        elements = {(0, 1): [L, C],}
        return sq.Circuit(elements)

    else:
        C   = sq.Capacitor(1, 'fF')
        L   = sq.Inductor(1/(1/1+1/Δ), 'nH')
        elements = {(0, 1): [L, C],}
        return sq.Circuit(elements)



In [24]:
n_eig = 3
trunc_num = 15
Δ=0.001

coupled_res     = premade_coupled_resonators    (Δ=Δ)
res             = premade_single_resonator      (Δ=Δ)

uncoupled_res   = premade_coupled_resonators    (Δ=0)
res_0           = premade_single_resonator      (Δ=0)

coupled_res     .set_trunc_nums([trunc_num, trunc_num])
uncoupled_res   .set_trunc_nums([trunc_num, trunc_num])
res             .set_trunc_nums([trunc_num])
res_0           .set_trunc_nums([trunc_num])

_ = coupled_res     .diag(n_eig)
_ = uncoupled_res   .diag(n_eig)
_ = res             .diag(n_eig)
_ = res_0           .diag(n_eig)


In [25]:
Q = res.charge_op(0)
Φ = res.flux_op(0)

Q_0 = res_0.charge_op(0)
Φ_0 = res_0.flux_op(0)


In [26]:
H_res_0 = 1/2 * Q_0**2/1e-15 + 1/2 * Φ_0**2/1e-9
H_res   = 1/2 * Q**2/1e-15 + 1/2 * (1+1/Δ) * Φ**2/1e-9
# H_res_0 = res_0.hamiltonian()
# H_res   = res.hamiltonian()

I = qt.identity(H_res.shape[0])

H_unc_res  = qt.tensor(H_res_0,I) + qt.tensor(I,H_res_0)


H_coup_res = qt.tensor(H_res,I)   + qt.tensor(I,H_res)   + (1/Δ/1e-9) * qt.tensor(Φ,Φ)
# H_coup_res = qt.tensor(H_res,I) + qt.tensor(I,H_res) + (1/Δ) * qt.tensor(Φ,Φ)

In [27]:
_ = uncoupled_res   .diag(n_eig, solver = 'numpy')
_ = coupled_res     .diag(n_eig, solver = 'numpy')
# H_eff_full = sq_ext.H_eff_p1(uncoupled_res,coupled_res )
H_eff_full = sq_ext.H_eff_p1_hamil(uncoupled_res.hamiltonian(), coupled_res.hamiltonian(), n_eig, solver='numpy' )


# H_eff_full -= H_eff_full[0,0]*np.eye(n_eig)

H_eff_frc = sq_ext.H_eff_p1_hamil(H_unc_res, H_coup_res, n_eig, solver='numpy')
H_eff_frc -= H_eff_frc[0,0]*np.eye(n_eig)

print(np.round(H_eff_full,8))
print('\n')
print(np.round(H_eff_frc, 8))
# print(np.round(np.abs(H_eff_full)-np.abs(H_eff_frc),4))

AttributeError: module 'Modules.SQcircuit_extensions' has no attribute 'H_eff_p1_hamil'

In [28]:
sq_ext.diag(H_unc_res, remove_ground=True)[0]

array([0.000000, 159.154943, 159.154943, 318.309886])

In [29]:
sq_ext.diag(uncoupled_res.hamiltonian(), remove_ground=True)[0]

array([0.000000, 159.154943, 159.154943, 318.309886])

In [30]:
#H_0 = H_unc_res.__array__()
#H = H_coup_res.__array__()
H_0 = uncoupled_res.hamiltonian().__array__()
H   = coupled_res.hamiltonian().__array__()

ψ_0 = sq_ext.diag(H_0, n_eig=len(H_0), real=False, solver='numpy')[1].T
ψ = sq_ext.diag(H, n_eig=len(H), real=False,   solver='numpy')[1].T


In [31]:
H_eff = np.zeros([n_eig,n_eig], dtype='complex')

for i in range(n_eig):
    for j in range(n_eig):
        for k in range(len(ψ)):
            for l in range(len(ψ)):
                H_eff[i,j] += (ψ_0[i].T.conj() @ ψ[k]) * (ψ[k].T.conj() @ H @ ψ[l]) * (ψ[l].T.conj() @ ψ_0[j])

KeyboardInterrupt: 

In [ ]:
U = ψ_0.conj().T @ ψ

In [ ]:
np.round(np.real(H),3)[0:n_eig+1,0:n_eig+1]/( 2 * np.pi * GHz)

In [ ]:
H2 = np.round(np.real(U.T @ H @ U),3)[0:n_eig+1,0:n_eig+1]/( 2 * np.pi * GHz)
H2

In [47]:
H_eff = np.zeros([n_eig,n_eig], dtype='complex')

for i in range(n_eig):
    for j in range(n_eig):
        for k in range(len(ψ)):
            H_eff[i,j] += (ψ_0[i].T.conj() @ ψ[k]) * (ψ[k].T.conj() @ H @ ψ[l]) * (ψ[l].T.conj() @ ψ_0[j])

In [ ]:
H_eff /= 2 * np.pi * GHz
#H_eff -= H_eff[0,0]*np.eye(n_eig)
if np.allclose(np.imag(H_eff),0):
    H_eff = np.real(H_eff)

In [ ]:
H_eff

In [79]:
ψ_0 = sq_ext.diag(H_unc_res, n_eig, real=False, solver='numpy')[1]
# ψ_0 = qt.Qobj(H_unc_res).eigenstates(sparse=True, eigvals=n_eig)[1]
# ψ_0 = np.array([ψ.__array__() for ψ in ψ_0])[:,:,0].T

# ψ_0_real = sq_ext.real_eigenvectors(ψ_0)
H_eff = ψ_0.conj().T @ H_coup_res.__array__() @ ψ_0 / GHz /2 /np.pi
# H_eff =np.array( [ [(ψ_0_i.dag() * H_unc_res * ψ_0_j) [0,0] / GHz /2 /np.pi for ψ_0_i in ψ_0] for ψ_0_j in ψ_0])

print(np.round(H_eff, 8))
# print(np.round(np.abs(H_eff), 8))

[[159.94873826+0.j  -0.        +0.j  -0.        +0.j]
 [ -0.        +0.j 319.89747651+0.j   0.79182544+0.j]
 [ -0.        +0.j   0.79182544+0.j 319.89747651+0.j]]


In [32]:
|H_eff_full = sq_ext.H_eff_p1(coupled_res,coupled_res, out=None)
# H_eff_full -= H_eff_full[0,0]*np.eye(n_eig)

H_eff_frc = sq_ext.H_eff_p1_hamil(H_coup_res, H_coup_res, n_eig, out=None)
# H_eff_frc -= H_eff_frc[0,0]*np.eye(n_eig)

print(np.abs(H_eff_full))
print(np.abs(H_eff_frc))
print(np.round(np.abs(H_eff_full-H_eff_frc),4))

SyntaxError: invalid syntax (2634790112.py, line 1)

In [33]:
ψ_full = np.array([ψ_i.__array__()[:, 0] for ψ_i in res_0._evecs]).T
H_full = res_0.hamiltonian().__array__()

print(np.abs(ψ_full.conj().T @ H_full @ ψ_full))


[[0.000000 0.000421 0.000661]
 [0.000421 999999999999.999756 0.000185]
 [0.000661 0.000185 1999999999999.999023]]


In [34]:
ψ_full = np.array([ψ_i.__array__()[:, 0] for ψ_i in uncoupled_res._evecs]).T
H_full = uncoupled_res.hamiltonian().__array__()

print(np.abs(ψ_full.conj().T @ H_full @ ψ_full))


[[0.000000 0.000000 0.000000]
 [0.000000 999999999999.999512 0.000000]
 [0.000000 0.000000 999999999999.999512]]


In [35]:
# ψ_frc = sq_ext.diag(H_unc_res,n_eig)[1]
ψ_frc = np.linalg.eigh(H_unc_res)[1]
print(np.abs(ψ_frc.conj().T @ H_unc_res.__array__() @ ψ_frc))


[[999999999999.999878 0.000000 0.000000 ... 0.000000 0.000000 0.000000]
 [0.000000 2000000000000.000977 0.000069 ... 0.000000 0.000000 0.000000]
 [0.000000 0.000069 2000000000000.000977 ... 0.000000 0.000000 0.000000]
 ...
 [0.000000 0.000000 0.000000 ... 26000000000000.000000 0.000000 0.000000]
 [0.000000 0.000000 0.000000 ... 0.000000 25999999999999.921875 0.000000]
 [0.000000 0.000000 0.000000 ... 0.000000 0.000000 26999999999999.980469]]


In [36]:
np.abs(uncoupled_res.hamiltonian_op('eig').__array__())

array([[0.000000, 0.000000, 0.000000],
       [0.000000, 999999999999.999512, 0.000000],
       [0.000000, 0.000000, 999999999999.999512]])

In [37]:
H_eff_full = sq_ext.H_eff_p1(res,res, out=None)
# H_eff_full -= H_eff_full[0,0]*np.eye(n_eig)

H_eff_frc = sq_ext.H_eff_p1_hamil(H_res, H_res, n_eig, out=None)
# H_eff_frc -= H_eff_frc[0,0]*np.eye(n_eig)

# print(np.abs(H_eff_full))
# print(np.abs(H_eff_frc))
print(np.round(np.abs(H_eff_full-H_eff_frc),4))


TypeError: H_eff_p1() missing 1 required positional argument: 'n_eig'

In [38]:
E = sq_ext.diag(H_coup_res , n_eig, out='GHz')[0]

print( (E-E[0]))
print( coupled_res.efreqs )

print( (E-E[0])[1])
print( coupled_res.efreqs[1] )


[0.000000 336.106068 866.139479]
[0.000000 159.154943 318.309886]
336.10606840306264
159.1549430918877


In [39]:
E = sq_ext.diag(H_unc_res , n_eig, out=None)[0]

print( (E-E[0]))
print( uncoupled_res._efreqs )

print( (E-E[0])[1])
print( uncoupled_res._efreqs[1] )


[0.000000 1000000000000.015015 1000000000000.019897]
[0.000000 999999999999.999512 999999999999.999512]
1000000000000.015
999999999999.9995


In [40]:
E = sq_ext.diag(H_res , n_eig, out=None)[0]
print( (E-E[0])[1])
print( res._efreqs[1] )


31638584039112.855
31638584039112.793


In [41]:
E = sq_ext.diag(H_res_0 , n_eig, out=None)[0]
print( E )
print( res_0._efreqs )


[500000000000.002197 1500000000000.001221 2500000000000.007812]
[0.001296 1000000000000.005249 1999999999999.998047]


In [42]:
Csh = 15
C   = 15
CJ  = 3
Lq  = 25
Lr  = 10

Cf = C/2 + Csh + CJ
C_f = Cf * 1e-15
C_r = C/2 * 1e-15

In [43]:
def sq_resonator(C=15, Lq=25, Lr=10, Δ=0.1):
    l = Lq * (Lq + 4 * Lr) - 4 * Δ ** 2
    resonator_elements = {
        (0, 1): [sq.Capacitor(C / 2, 'fF'), sq.Inductor(l / Lq, 'nH')],
    }
    return sq.Circuit(resonator_elements)


def KIT_fluxonium_no_JJ(C=15, CJ=3, Csh=15, Lq=25, Lr=10, Δ=0.1):
    l = Lq * (Lq + 4 * Lr) - 4 * Δ ** 2
    fluxonium_elements = {
        (0, 1): [sq.Capacitor(C / 2 + Csh + CJ, 'fF'),
                 sq.Inductor(l / (Lq + 4 * Lr), 'nH')],
    }
    return sq.Circuit(fluxonium_elements)

def KIT_qubit_no_JJ(C = 15, CJ = 3, Csh= 15 , Lq = 25, Lr = 10, Δ = 0.1, φ_ext=0.5):

    # Initialize loop(s)
    # loop = sq.Loop(φ_ext)

    # Circuit components
    C_01 = sq.Capacitor(C,       'fF')
    C_02 = sq.Capacitor(C,       'fF')
    C_12 = sq.Capacitor(CJ+Csh,  'fF')
    L_03 = sq.Inductor(Lr,       'nH')
    L_31 = sq.Inductor(Lq/2 - Δ, 'nH')#,  loops=[loop])
    L_23 = sq.Inductor(Lq/2 + Δ, 'nH')#,  loops=[loop])

    elements = {
        (0, 3): [L_03],
        (0, 1): [C_01],
        (0, 2): [C_02],
        (3, 1): [L_31],
        (1, 2): [C_12],
        (2, 3): [L_23],
    }

    # Create and return the circuit
    return sq.Circuit(elements)

def sq_fluxonium(C = 15, CJ = 3, Csh= 15, Lq = 25, Lr = 10, Δ = 0.1, EJ = 10.0, φ_ext=0.5):
    l = Lq * (Lq + 4 * Lr) - 4 * Δ ** 2
    loop_fluxonium = sq.Loop(φ_ext)
    fluxonium_elements = {
        (0, 1): [sq.Capacitor(C / 2 + Csh + CJ, 'fF'),
                 sq.Inductor(l / (Lq + 4 * Lr), 'nH', loops=[loop_fluxonium]),
                 sq.Junction(EJ, 'GHz', loops=[loop_fluxonium])],
    }
    return sq.Circuit(fluxonium_elements)

def sq_qubit(C = 15, CJ = 3, Csh= 15 , Lq = 25, Lr = 10, Δ = 0.1, EJ = 10.0, φ_ext=0.5):

    # Initialize loop(s)
    loop = sq.Loop(φ_ext)

    # Circuit components
    C_01 = sq.Capacitor(C,       'fF')
    C_02 = sq.Capacitor(C,       'fF')
    C_12 = sq.Capacitor(CJ+Csh,  'fF')
    L_03 = sq.Inductor(Lr,       'nH')
    L_31 = sq.Inductor(Lq/2 - Δ, 'nH',  loops=[loop])
    L_23 = sq.Inductor(Lq/2 + Δ, 'nH',  loops=[loop])
    JJ_12= sq.Junction(EJ,       'GHz', loops=[loop])

    elements = {
        (0, 3): [L_03],
        (0, 1): [C_01],
        (0, 2): [C_02],
        (3, 1): [L_31],
        (1, 2): [C_12, JJ_12],
        (2, 3): [L_23],
    }

    # Create and return the circuit
    return sq.Circuit(elements)


In [62]:
n_eig = 4
trunc_num = 20
Δ=10

res     = sq_resonator          (Δ=Δ)
flu     = sq_fluxonium   (Δ=Δ)
qubit   = sq_qubit      (Δ=Δ)
# flu     = KIT_fluxonium_no_JJ    (Δ=Δ)
# qubit   = KIT_qubit_no_JJ        (Δ=Δ)

res_0   = sq_resonator          (Δ=0)
flu_0   = sq_fluxonium    (Δ=0)
qubit_0 = sq_qubit       (Δ=0)
# flu_0   = KIT_fluxonium_no_JJ    (Δ=0)
# qubit_0 = KIT_qubit_no_JJ        (Δ=0)
#
res     .set_trunc_nums([trunc_num])
flu     .set_trunc_nums([trunc_num])
# qubit   .set_trunc_nums([1, trunc_num,trunc_num])
qubit   .set_trunc_nums( [trunc_num,trunc_num])
res_0   .set_trunc_nums([trunc_num])
flu_0   .set_trunc_nums([trunc_num])
# qubit_0 .set_trunc_nums([1, trunc_num,trunc_num])
qubit_0 .set_trunc_nums([trunc_num,trunc_num])

_ = res     .diag(n_eig)
_ = flu     .diag(n_eig)
_ = qubit   .diag(n_eig)
_ = res_0   .diag(n_eig)
_ = flu_0   .diag(n_eig)
_ = qubit_0 .diag(n_eig)


In [63]:
l = Lq*(Lq+4*Lr) - 4*Δ**2
L_r = l/Lq * 1e-9
L_f = l/(Lq+4*Lr) * 1e-9
L_c = l/Δ * 1e-9

L_r_0 = (Lq+4*Lr) * 1e-9
L_f_0 = Lq * 1e-9


In [64]:
Q_res = res.charge_op(0)
Φ_res = res.flux_op(0)

Q_res_0 = res_0.charge_op(0)
Φ_res_0 = res_0.flux_op(0)

Q_flu = flu.charge_op(0)
Φ_flu = flu.flux_op(0)

Q_flu_0 = flu_0.charge_op(0)
Φ_flu_0 = flu_0.flux_op(0)


In [65]:
H_res_0 = 1/2 * Q_res_0**2 / C_r  + 1/2 * Φ_res_0**2 / L_r_0
# H_res = 1/2 * Q_res**2 / C_r  + 1/2 * Φ_res**2 / L_r
H_res = res.hamiltonian()

H_flu_0 = 1/2 * Q_flu_0**2 / C_f + 1/2 * Φ_flu_0**2 / L_f_0
# H_flu = 1/2 * Q_flu**2 / C_f + 1/2 * Φ_flu**2 / L_f
H_flu = flu.hamiltonian()

I_res = qt.identity(H_res.shape[0])
I_flu = qt.identity(H_flu.shape[0])

H_qubit_0 = qt.tensor(H_res_0,I_res) + qt.tensor(I_res,H_flu_0)
H_qubit = qt.tensor(H_res,I_flu) + qt.tensor(I_res,H_flu) + qt.tensor(Φ_res,Φ_flu) * 2 * Δ / l / 1e-9


In [66]:
Φ, Q = sq_ext.get_node_variables(qubit , 'FC', isolated='True')


In [72]:
E, ψ = sq_ext.diag(H_qubit , n_eig, out='GHz')
ψ_sq = np.array([ψ_i.__array__()[:, 0] for ψ_i in qubit._evecs])

print( E-E[0])
print( qubit.efreqs -qubit.efreqs[0] )
for i in range(n_eig):
    print(f'Energy error in state{i} = {np.abs((E-E[0])[i]- (qubit.efreqs[i]-qubit.efreqs[0]))}')
    print(f'Wavefunction error in state{i} = {1 - np.abs(ψ[:,i].conj().T @ qubit._evecs[i].__array__())[0]}')



[0.000000 1.699355 5.320950 8.641732]
[0.000000 1.699355 5.320950 8.641732]
Energy error in state0 = 0.0
Wavefunction error in state0 = 0.012107992820037716
Energy error in state1 = 3.1000439548733993e-08
Wavefunction error in state1 = 0.04357105839814435
Energy error in state2 = 2.565301571166856e-08
Wavefunction error in state2 = 0.14309355272952817
Energy error in state3 = 1.199621735281653e-09
Wavefunction error in state3 = 0.7640292945706324


In [74]:
E, ψ = sq_ext.diag(H_qubit , n_eig, out='GHz')
ψ_sq = np.array([ψ_i.__array__()[:, 0] for ψ_i in qubit._evecs])

print( E-E[0])
print( qubit.efreqs -qubit.efreqs[0] )
for i in range(n_eig):
    print(f'Energy error in state{i} = {np.abs((E-E[0])[i]- (qubit.efreqs[i]-qubit.efreqs[0]))}')
    print(f'Wavefunction error in state{i} = {1 - np.abs(ψ[:,i].conj().T @ qubit._evecs[i].__array__())[0]}')



[0.000000 1.699355 5.320950 8.641732]
[0.000000 1.699355 5.320950 8.641732]
Energy error in state0 = 0.0
Wavefunction error in state0 = 0.01210799282003927
Energy error in state1 = 3.100059053906534e-08
Wavefunction error in state1 = 0.043571058398148343
Energy error in state2 = 2.5653076107801098e-08
Wavefunction error in state2 = 0.14309355272953217
Energy error in state3 = 1.199817134533987e-09
Wavefunction error in state3 = 0.7640292945706321


In [69]:
E = sq_ext.diag(H_qubit_0 , n_eig, out='GHz')[0]

print( E-E [0])
print( qubit_0.efreqs )

print( (E-E[0])[1])
print( qubit_0.efreqs[1] )


[0.000000 6.303475 7.208299 12.606950]
[6.706952 8.652341 12.868154 13.915251]
6.303475034201443
8.652340971053187


In [70]:
E = sq_ext.diag(H_res , n_eig, out='GHz')[0]
print(E-E[0] )
print( res.efreqs )

print( (E-E[0])[1])
print( res.efreqs[1] )


[0.000000 8.302167 16.604334 24.906501]
[0.000000 8.302167 16.604334 24.906501]
8.302166901893436
8.302166901893532


In [71]:
E = sq_ext.diag(H_flu_0, n_eig, out='GHz')[0]
print(E-E[0])
print( flu_0.efreqs )


[0.000000 6.303475 12.606950 18.910425]
[6.706952 8.652341 12.868154 17.500105]


In [61]:
E = sq_ext.diag(H_res_0 , n_eig, out='GHz')[0]
print(E-E[0] )
print( res_0.efreqs )






[0.000000 7.208299 14.416599 21.624898]
[0.000000 7.208299 14.416599 21.624898]
