In [1]:
import Modules.SQcircuit_extensions as sq_ext
import Modules.figures as figs
import SQcircuit as sq
import numpy as np
import matplotlib.pyplot as plt
from importlib import reload
from scipy.linalg import eigh
import qutip as qt
import sympy as sym

%matplotlib ipympl
plt.rcParams['text.usetex'] = False
reload(sq_ext)
reload(sq)
reload(figs)
np.set_printoptions(linewidth=300, formatter={'float': '{:.12f}'.format})

# Comparison of sqcircuit, numeric and spin-boson models vs truncation

In [2]:
Cc = 0.1
n_eig = 3
# nmax_r_values = np.array([7, 7, 9,  9, 11, 11, 13, 13, 15])
# nmax_f_values = np.array([7, 9, 9, 11, 11, 13, 13, 15, 15])
nmax_r_values = np.array([3, 3, 3, 3, 3])
nmax_f_values = np.array([5, 6, 7, 8, 9])

E_sq = []
E_n  = []

for nmax_r, nmax_f in zip(nmax_r_values, nmax_f_values):
    print(nmax_f)
    
    H_n = sq_ext.hamiltonian_qubit_C_qubit_C_qubit(nmax_r=nmax_r, nmax_f=nmax_f, Cc=Cc, periodic=False)
    E = sq_ext.diag(H_n, n_eig, out='GHz')[0]
    E_n.append(E-E[0])
    del(H_n)
    
    if nmax_f >= 9:
        continue
    else:
        # H_sq = sq_ext.sq_qubit_C_qubit_C_qubit(Cc, nmax_r=nmax_r, nmax_f=nmax_f)
        H_sq = sq_ext.sq_qubit_C_qubit_C_qubit_not_periodic(Cc, nmax_r=nmax_r, nmax_f=nmax_f)
        H_sq.diag(n_eig)
        E_sq.append(H_sq.efreqs-H_sq.efreqs[0])
        del(H_sq)
    
E_sq = np.array(E_sq )
E_n  = np.array(E_n  )

5
6


KeyboardInterrupt: 

In [ ]:
fig, [ax1,ax2] = plt.subplots(ncols=2)

for i, ax in enumerate([ax1,ax2]):
    ax.plot(E_sq[:,i+1], 'r')
    ax.plot(E_n [:,i+1], 'g')

fig.show()

In [ ]:
Cc_values = np.geomspace( 1e-3, 1, 10)
n_eig = 3
nmax_r = 4
nmax_f = 12 

E_sq = []
E_n  = []
E_sb = []

for Cc in Cc_values:
    print(Cc)
    
    H_n = sq_ext.hamiltonian_qubit_C_qubit(nmax_r=nmax_r, nmax_f=nmax_f, Cc=Cc)
    E = sq_ext.diag(H_n, n_eig, out='GHz')[0]
    E_n.append(E-E[0])
    del(H_n)

    H_sb = sq_ext.spin_boson_qubit_C_qubit(nmax_r=nmax_r, nmax_f=nmax_f, Cc=Cc)
    E = eigh(H_sb, eigvals_only=True)
    E_sb.append(E-E[0])
    del(H_sb)
    
    H_sq = sq_ext.sq_qubit_C_qubit(Cc, nmax_r=nmax_r, nmax_f=nmax_f)
    H_sq.diag(n_eig)
    E_sq.append(H_sq.efreqs-H_sq.efreqs[0])
    del(H_sq)
    
E_sq = np.array(E_sq )
E_n  = np.array(E_n  )
E_sb = np.array(E_sb )   

In [ ]:
fig, [ax1, ax2] = plt.subplots(ncols=2, dpi =200)

for i, ax in enumerate([ax1, ax2]):
    ax.plot(Cc_values, E_sq[:, i + 1], 'r')
    ax.plot(Cc_values, E_n[:, i + 1], '--g')
    ax.plot(Cc_values, E_sb[:, i + 1], 'b')
    
ax.set_xscale('log')
fig.tight_layout()
fig.show()

In [31]:
sq_ext = reload(sq_ext)
Cc = 1e-1
nmax_r = 4
nmax_f = 12 
H_0 = sq_ext.hamiltonian_qubit_C_qubit_C_qubit(Cc=0 , nmax_r=nmax_r, nmax_f=nmax_f, only_outer=True)
H = sq_ext.hamiltonian_qubit_C_qubit_C_qubit(Cc=0 , nmax_r=nmax_r, nmax_f=nmax_f, only_outer=True)
# H   = sq_ext.hamiltonian_qubit_C_qubit_C_qubit(Cc=Cc, nmax_r=nmax_r, nmax_f=nmax_f)

In [38]:
ψ_0 = qt.Qobj(H).eigenstates(sparse=True, eigvals=4, phase_fix=0)[1]

In [39]:
ψ_0

array([Quantum object: dims = [[4, 12, 4, 12, 4, 12], [1, 1, 1, 1, 1, 1]], shape = (110592, 1), type = ket
       Qobj data =
         (0, 0)	(0.006875353105680666+0j)
         (2, 0)	(0.003054374746410276+0j)
         (4, 0)	(0.0007115585332827918+0j)
         (6, 0)	(-1.5213440643590097e-06+0j)
         (8, 0)	(-2.5613754432700424e-05+0j)
         (10, 0)	(3.3792457837270778e-06+0j)
         (13, 0)	(-2.1030943691910853e-05+0j)
         (15, 0)	(-1.1097930832716464e-05+0j)
         (17, 0)	(-2.2321861219466753e-06+0j)
         (19, 0)	(1.9011336563957796e-07+0j)
         (21, 0)	(8.503138672957329e-08+0j)
         (23, 0)	(-2.032549462929722e-08+0j)
         (24, 0)	(4.2478273937235394e-08+0j)
         (26, 0)	(6.548990682608252e-08+0j)
         (28, 0)	(3.113797853740747e-08+0j)
         (30, 0)	(4.524821303383063e-09+0j)
         (32, 0)	(-1.0089368551665342e-09+0j)
         (34, 0)	(-1.4397000925621668e-10+0j)
         (37, 0)	(-1.8126812952176564e-10+0j)
         (39, 0)	(-1.8652

In [36]:
n_eig = 4

H_eff = np.zeros((n_eig, n_eig), dtype=complex)

for i in range(n_eig):
    for j in range(n_eig):
        H_eff[i, j] = (ψ_0[i].dag()
                       * H * ψ_0 [j]).data[0, 0]

In [37]:
H_eff/2/np.pi/1e9

array([[ 1.34138723e+01-4.27213812e-16j,  4.52497578e-03+2.88174911e-01j, -2.24220859e-01+7.29161469e-02j,  7.77474645e-02+5.56983489e-02j],
       [ 4.52497578e-03-2.88174911e-01j,  1.34138723e+01+4.11595312e-16j, -8.16947244e-02+6.42166788e-01j,  2.61531017e-01+1.32199271e-01j],
       [-2.24220859e-01-7.29161469e-02j, -8.16947244e-02-6.42166788e-01j,  1.34138723e+01+1.23634159e-16j,  4.33855370e-02+5.36287566e-02j],
       [ 7.77474645e-02-5.56983489e-02j,  2.61531017e-01-1.32199271e-01j,  4.33855370e-02-5.36287566e-02j,  1.34138723e+01-6.70086970e-16j]])

In [24]:
ψ_0.dag() * qt.Qobj(H) * ψ_0

AttributeError: 'numpy.ndarray' object has no attribute 'dag'

In [3]:
H_eff = sq_ext.H_eff_p1a(H_0, H, 4)

MemoryError: Unable to allocate 182. GiB for an array with shape (110592, 110592) and data type complex128

In [18]:
np.round(H_eff,3)

array([[ 2.757515e+03-0.j   ,  0.000000e+00-0.j   ,  0.000000e+00+0.j   , -8.400000e-02-0.j   ],
       [ 0.000000e+00+0.j   ,  2.850696e+03-0.j   ,  8.200000e-02-0.014j,  0.000000e+00-0.j   ],
       [ 0.000000e+00-0.j   ,  8.200000e-02+0.014j,  2.850727e+03-0.j   , -0.000000e+00+0.j   ],
       [-8.400000e-02+0.j   ,  0.000000e+00+0.j   , -0.000000e+00-0.j   ,  2.943908e+03-0.j   ]])

In [22]:
sq_ext.diag(H_0, 2, out='GHz')[0]

array([20.120808502260, 22.066170039274])

In [23]:
sq_ext.diag(H, 2, out='GHz')[0]

array([20.126025274038, 22.065877303801])

In [36]:
sq_ext.diag(H, 2, out='GHz')[0]

array([20.126025274038, 22.065877303801])

In [32]:
H_eff = sq_ext.H_eff_SWT(H_0, H, 4)

In [34]:
sq_ext.diag(H_eff, 2, out='GHz')[0]

array([20.126025274038, 22.065877303801])