In [2]:
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt

In [3]:
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

In [4]:
C = sym.Matrix([[C_R+C_C, 0      , -C_C/4 , -C_C/4 ],
                [0      , C_F+C_C, -C_C/4 , -C_C/4 ],
                [-C_C/4 , -C_C/4 , C_R+C_C, 0      ],
                [-C_C/4 , -C_C/4 , 0      , C_F+C_C] ])

In [5]:
C_inv = C**-1

In [6]:
sym.simplify(C_inv)

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [7]:
sym.simplify(C_inv )

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [8]:
sym.factor(C_inv[0,0])

(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/((2*C_C**2 + 3*C_C*C_F + 3*C_C*C_R + 4*C_F*C_R)*(6*C_C**2 + 5*C_C*C_F + 5*C_C*C_R + 4*C_F*C_R))

In [9]:
C_inv[0,0] - C_inv[2,2]

0

In [10]:
Csh = 15
C   = 15
Cg  = 10
CJ  = 3
Cc  = 10

In [11]:
a=np.array( C_inv.subs({C_C:Cc, C_R:C/2, C_F:C/2 + Csh + CJ}).evalf() )

In [12]:
a/a[0,0]

array([[1.00000000000000, 0.0152487268751618, 0.145035532410737,
        0.0714963892165607],
       [0.0152487268751618, 0.485225997640763, 0.0714963892165607,
        0.0352446989095722],
       [0.145035532410737, 0.0714963892165607, 1.00000000000000,
        0.0152487268751618],
       [0.0714963892165607, 0.0352446989095722, 0.0152487268751618,
        0.485225997640763]], dtype=object)

In [13]:
C_R = C/2
C_C = Cc
C_F = C/2 + Csh + CJ
C   = np.array([  [C_R + C_C, 0, -C_C / 4, -C_C / 4],
                  [0, C_F + C_C, -C_C / 4, -C_C / 4],
                  [-C_C / 4, -C_C / 4, C_R + C_C, 0],
                  [-C_C / 4, -C_C / 4, 0, C_F + C_C]])

In [14]:
C

array([[17.5,  0. , -2.5, -2.5],
       [ 0. , 35.5, -2.5, -2.5],
       [-2.5, -2.5, 17.5,  0. ],
       [-2.5, -2.5,  0. , 35.5]])

In [20]:
np.linalg.inv(C)**-1

array([[  16.9586702 , 1112.13679245,  116.92769292,  237.19617706],
       [1112.13679245,   34.95004447,  237.19617706,  481.16938776],
       [ 116.92769292,  237.19617706,   16.9586702 , 1112.13679245],
       [ 237.19617706,  481.16938776, 1112.13679245,   34.95004447]])

In [23]:
C_F + C_C

35.5

In [24]:
C_R + C_C

17.5

In [18]:
# Define the symbols
alpha = sym.symbols('\\alpha', real=True, positive = True, nonzero=True)

# Create a 6x6 matrix based on the given pattern
C_mat = sym.Matrix(12,12, lambda i, j: 1 if i == j else alpha if abs(i-j) == 2 else 0)

C_mat

Matrix([
[     1,      0, \alpha,      0,      0,      0,      0,      0,      0,      0,      0,      0],
[     0,      1,      0, \alpha,      0,      0,      0,      0,      0,      0,      0,      0],
[\alpha,      0,      1,      0, \alpha,      0,      0,      0,      0,      0,      0,      0],
[     0, \alpha,      0,      1,      0, \alpha,      0,      0,      0,      0,      0,      0],
[     0,      0, \alpha,      0,      1,      0, \alpha,      0,      0,      0,      0,      0],
[     0,      0,      0, \alpha,      0,      1,      0, \alpha,      0,      0,      0,      0],
[     0,      0,      0,      0, \alpha,      0,      1,      0, \alpha,      0,      0,      0],
[     0,      0,      0,      0,      0, \alpha,      0,      1,      0, \alpha,      0,      0],
[     0,      0,      0,      0,      0,      0, \alpha,      0,      1,      0, \alpha,      0],
[     0,      0,      0,      0,      0,      0,      0, \alpha,      0,      1,      0, \alpha],
[     0,   

In [19]:
C_inv = C_mat **-1

In [13]:
sym.simplify(C_inv)

Matrix([
[    -1/(\alpha**2 - 1),                      0, \alpha/(\alpha**2 - 1),                      0],
[                     0,     -1/(\alpha**2 - 1),                      0, \alpha/(\alpha**2 - 1)],
[\alpha/(\alpha**2 - 1),                      0,     -1/(\alpha**2 - 1),                      0],
[                     0, \alpha/(\alpha**2 - 1),                      0,     -1/(\alpha**2 - 1)]])

In [17]:
sym.simplify(C_inv)

Matrix([
[(\alpha**2 - 1)/(2*\alpha**2 - 1),                                 0, \alpha/(2*\alpha**2 - 1),                        0,      -\alpha**2/(2*\alpha**2 - 1),                                 0],
[                                0, (\alpha**2 - 1)/(2*\alpha**2 - 1),                        0, \alpha/(2*\alpha**2 - 1),                                 0,      -\alpha**2/(2*\alpha**2 - 1)],
[         \alpha/(2*\alpha**2 - 1),                                 0,     -1/(2*\alpha**2 - 1),                        0,          \alpha/(2*\alpha**2 - 1),                                 0],
[                                0,          \alpha/(2*\alpha**2 - 1),                        0,     -1/(2*\alpha**2 - 1),                                 0,          \alpha/(2*\alpha**2 - 1)],
[     -\alpha**2/(2*\alpha**2 - 1),                                 0, \alpha/(2*\alpha**2 - 1),                        0, (\alpha**2 - 1)/(2*\alpha**2 - 1),                                 0],
[                    

In [20]:
sym.simplify(C_inv)

Matrix([
[  (-3*\alpha**4 + 4*\alpha**2 - 1)/(\alpha**6 - 6*\alpha**4 + 5*\alpha**2 - 1),                                                                              0, (\alpha**5 - 3*\alpha**3 + \alpha)/(\alpha**6 - 6*\alpha**4 + 5*\alpha**2 - 1),                                                                              0,          (2*\alpha**4 - \alpha**2)/(\alpha**6 - 6*\alpha**4 + 5*\alpha**2 - 1),                                                                              0,           (-\alpha**5 + \alpha**3)/(\alpha**6 - 6*\alpha**4 + 5*\alpha**2 - 1),                                                                              0,                         -\alpha**4/(\alpha**6 - 6*\alpha**4 + 5*\alpha**2 - 1),                                                                              0,                          \alpha**5/(\alpha**6 - 6*\alpha**4 + 5*\alpha**2 - 1),                                                                              0],
[                            

In [25]:
# Define the symbols
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

# Create a 6x6 matrix based on the given pattern
C_mat = sym.Matrix(4,4, lambda i, j: C_R+C_C/2 if (i == j and np.mod(i,2)==0) else C_F+C_C/2 if (i == j and np.mod(i,2)!=0)  else -C_C/2 if abs(i-j) == 2 else 0)

C_mat

Matrix([
[C_C/2 + C_R,           0,      -C_C/2,           0],
[          0, C_C/2 + C_F,           0,      -C_C/2],
[     -C_C/2,           0, C_C/2 + C_R,           0],
[          0,      -C_C/2,           0, C_C/2 + C_F]])

In [26]:
C_inv = C_mat **-1

In [31]:
sym.simplify(C_inv)

Matrix([
[(C_C/2 + C_R)/(C_R*(C_C + C_R)),                               0,         C_C/(2*C_R*(C_C + C_R)),                               0],
[                              0, (C_C/2 + C_F)/(C_F*(C_C + C_F)),                               0,         C_C/(2*C_F*(C_C + C_F))],
[        C_C/(2*C_R*(C_C + C_R)),                               0, (C_C/2 + C_R)/(C_R*(C_C + C_R)),                               0],
[                              0,         C_C/(2*C_F*(C_C + C_F)),                               0, (C_C/2 + C_F)/(C_F*(C_C + C_F))]])

In [30]:
sym.print_latex(sym.simplify(C_inv))

\left[\begin{matrix}\frac{\frac{C_{C}}{2} + C_{R}}{C_{R} \left(C_{C} + C_{R}\right)} & 0 & \frac{C_{C}}{2 C_{R} \left(C_{C} + C_{R}\right)} & 0\\0 & \frac{\frac{C_{C}}{2} + C_{F}}{C_{F} \left(C_{C} + C_{F}\right)} & 0 & \frac{C_{C}}{2 C_{F} \left(C_{C} + C_{F}\right)}\\\frac{C_{C}}{2 C_{R} \left(C_{C} + C_{R}\right)} & 0 & \frac{\frac{C_{C}}{2} + C_{R}}{C_{R} \left(C_{C} + C_{R}\right)} & 0\\0 & \frac{C_{C}}{2 C_{F} \left(C_{C} + C_{F}\right)} & 0 & \frac{\frac{C_{C}}{2} + C_{F}}{C_{F} \left(C_{C} + C_{F}\right)}\end{matrix}\right]
