In [2]:
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def neglect_terms(expr, N):
    # Function to neglect terms of order N and higher in a polynomial
    # Split the expression into numerator and denominator
    num, denom = expr.as_numer_denom()
    # Process numerator and denominator to remove terms of order N and higher
    num_neglected = sum(coeff * term for term, coeff in num.as_coefficients_dict().items() if all(pow < N for var, pow in term.as_powers_dict().items()))
    denom_neglected = sum(coeff * term for term, coeff in denom.as_coefficients_dict().items() if all(pow < N for var, pow in term.as_powers_dict().items()))
    # Reconstruct the fraction
    return num_neglected / denom_neglected

def neglect_terms_in_matrix(matrix, N):
    # Process each element in the matrix
    processed_matrix = matrix.applyfunc(lambda x: neglect_terms(x, N))

    return processed_matrix

In [66]:
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

In [67]:
C = sym.Matrix([[C_R+C_C, 0      , -C_C/4 , -C_C/4 ],
                [0      , C_F+C_C, -C_C/4 , -C_C/4 ],
                [-C_C/4 , -C_C/4 , C_R+C_C, 0      ],
                [-C_C/4 , -C_C/4 , 0      , C_F+C_C] ])

In [4]:
C_inv = C**-1

In [5]:
sym.simplify(C_inv)

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [6]:
sym.simplify(C_inv )

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [7]:
sym.factor(C_inv[0,0])

(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/((2*C_C**2 + 3*C_C*C_F + 3*C_C*C_R + 4*C_F*C_R)*(6*C_C**2 + 5*C_C*C_F + 5*C_C*C_R + 4*C_F*C_R))

In [8]:
C_inv[0,0] - C_inv[2,2]

0

In [9]:
Csh = 15
C   = 15
Cg  = 10
CJ  = 3
Cc  = 10

In [10]:
a=np.array( C_inv.subs({C_C:Cc, C_R:C/2, C_F:C/2 + Csh + CJ}).evalf() )

In [11]:
a/a[0,0]

array([[1.00000000000000, 0.0152487268751618, 0.145035532410737,
        0.0714963892165607],
       [0.0152487268751618, 0.485225997640763, 0.0714963892165607,
        0.0352446989095722],
       [0.145035532410737, 0.0714963892165607, 1.00000000000000,
        0.0152487268751618],
       [0.0714963892165607, 0.0352446989095722, 0.0152487268751618,
        0.485225997640763]], dtype=object)

In [12]:
C_R = C/2
C_C = Cc
C_F = C/2 + Csh + CJ
C   = np.array([  [C_R + C_C, 0, -C_C / 4, -C_C / 4],
                  [0, C_F + C_C, -C_C / 4, -C_C / 4],
                  [-C_C / 4, -C_C / 4, C_R + C_C, 0],
                  [-C_C / 4, -C_C / 4, 0, C_F + C_C]])

In [13]:
C

array([[17.5,  0. , -2.5, -2.5],
       [ 0. , 35.5, -2.5, -2.5],
       [-2.5, -2.5, 17.5,  0. ],
       [-2.5, -2.5,  0. , 35.5]])

In [14]:
np.linalg.inv(C)**-1

array([[  16.9586702 , 1112.13679245,  116.92769292,  237.19617706],
       [1112.13679245,   34.95004447,  237.19617706,  481.16938776],
       [ 116.92769292,  237.19617706,   16.9586702 , 1112.13679245],
       [ 237.19617706,  481.16938776, 1112.13679245,   34.95004447]])

In [15]:
C_F + C_C

35.5

In [16]:
C_R + C_C

17.5

In [56]:
# Define the symbols
alpha= sym.symbols('\\alpha', real=True, positive = True, nonzero=True)
N=10
C_mat = sym.Matrix(N,N, lambda i, j: 1+alpha if i == j else -alpha if abs(i-j) == 2 else -alpha if ((i==N-1 and j==0) or (i==0 and j==N-1) )  else 0)
# C_mat = sym.Matrix(N,N, lambda i, j: 1+alpha if i == j else -alpha if abs(i-j) == 2  else 0)

C_mat

Matrix([
[\alpha + 1,          0,    -\alpha,          0,          0,          0,          0,          0,          0,    -\alpha],
[         0, \alpha + 1,          0,    -\alpha,          0,          0,          0,          0,          0,          0],
[   -\alpha,          0, \alpha + 1,          0,    -\alpha,          0,          0,          0,          0,          0],
[         0,    -\alpha,          0, \alpha + 1,          0,    -\alpha,          0,          0,          0,          0],
[         0,          0,    -\alpha,          0, \alpha + 1,          0,    -\alpha,          0,          0,          0],
[         0,          0,          0,    -\alpha,          0, \alpha + 1,          0,    -\alpha,          0,          0],
[         0,          0,          0,          0,    -\alpha,          0, \alpha + 1,          0,    -\alpha,          0],
[         0,          0,          0,          0,          0,    -\alpha,          0, \alpha + 1,          0,    -\alpha],
[         0,   

In [57]:
sym.print_latex(sym.simplify(C_mat))

\left[\begin{matrix}\alpha + 1 & 0 & - \alpha & 0 & 0 & 0 & 0 & 0 & 0 & - \alpha\\0 & \alpha + 1 & 0 & - \alpha & 0 & 0 & 0 & 0 & 0 & 0\\- \alpha & 0 & \alpha + 1 & 0 & - \alpha & 0 & 0 & 0 & 0 & 0\\0 & - \alpha & 0 & \alpha + 1 & 0 & - \alpha & 0 & 0 & 0 & 0\\0 & 0 & - \alpha & 0 & \alpha + 1 & 0 & - \alpha & 0 & 0 & 0\\0 & 0 & 0 & - \alpha & 0 & \alpha + 1 & 0 & - \alpha & 0 & 0\\0 & 0 & 0 & 0 & - \alpha & 0 & \alpha + 1 & 0 & - \alpha & 0\\0 & 0 & 0 & 0 & 0 & - \alpha & 0 & \alpha + 1 & 0 & - \alpha\\0 & 0 & 0 & 0 & 0 & 0 & - \alpha & 0 & \alpha + 1 & 0\\- \alpha & 0 & 0 & 0 & 0 & 0 & 0 & - \alpha & 0 & \alpha + 1\end{matrix}\right]


In [58]:
C_inv = C_mat **-1
# C_inv = sym.simplify(C_inv)

In [59]:
C_inv[0,0]

(-4*\alpha**8 - 10*\alpha**7 + 14*\alpha**6 + 39*\alpha**5 + 5*\alpha**4 - 35*\alpha**3 - 29*\alpha**2 - 9*\alpha - 1)/(\alpha**10 + 4*\alpha**9 - 18*\alpha**8 - 36*\alpha**7 + 35*\alpha**6 + 84*\alpha**5 + 14*\alpha**4 - 48*\alpha**3 - 36*\alpha**2 - 10*\alpha - 1)

In [60]:
C_inv

Matrix([
[    (-4*\alpha**8 - 10*\alpha**7 + 14*\alpha**6 + 39*\alpha**5 + 5*\alpha**4 - 35*\alpha**3 - 29*\alpha**2 - 9*\alpha - 1)/(\alpha**10 + 4*\alpha**9 - 18*\alpha**8 - 36*\alpha**7 + 35*\alpha**6 + 84*\alpha**5 + 14*\alpha**4 - 48*\alpha**3 - 36*\alpha**2 - 10*\alpha - 1),                                                                 (\alpha**9 + 2*\alpha**8 - 3*\alpha**7 - 4*\alpha**6 - \alpha**5)/(\alpha**10 + 4*\alpha**9 - 18*\alpha**8 - 36*\alpha**7 + 35*\alpha**6 + 84*\alpha**5 + 14*\alpha**4 - 48*\alpha**3 - 36*\alpha**2 - 10*\alpha - 1),                    (-4*\alpha**8 + 2*\alpha**7 + 20*\alpha**6 + 9*\alpha**5 - 20*\alpha**4 - 22*\alpha**3 - 8*\alpha**2 - \alpha)/(\alpha**10 + 4*\alpha**9 - 18*\alpha**8 - 36*\alpha**7 + 35*\alpha**6 + 84*\alpha**5 + 14*\alpha**4 - 48*\alpha**3 - 36*\alpha**2 - 10*\alpha - 1),                                               (\alpha**9 + 3*\alpha**8 - \alpha**7 - 7*\alpha**6 - 5*\alpha**5 - \alpha**4)/(\alpha**10 + 4*\alpha**9 - 18*\alph

In [61]:
neglect_terms_in_matrix(C_inv,2)

Matrix([
[(-9*\alpha - 1)/(-10*\alpha - 1),                                0,         -\alpha/(-10*\alpha - 1),                                0,                                0,                                0,                                0,                                0,                                0,         -\alpha/(-10*\alpha - 1)],
[                               0, (-9*\alpha - 1)/(-10*\alpha - 1),                                0,         -\alpha/(-10*\alpha - 1),                                0,                                0,                                0,                                0,                                0,                                0],
[        -\alpha/(-10*\alpha - 1),                                0, (-9*\alpha - 1)/(-10*\alpha - 1),                                0,         -\alpha/(-10*\alpha - 1),                                0,                                0,                                0,                                0, 

In [63]:
neglect_terms_in_matrix(C_inv,3)

Matrix([
[(-29*\alpha**2 - 9*\alpha - 1)/(-36*\alpha**2 - 10*\alpha - 1),                                                              0,        (-8*\alpha**2 - \alpha)/(-36*\alpha**2 - 10*\alpha - 1),                                                              0,                     -\alpha**2/(-36*\alpha**2 - 10*\alpha - 1),                                                              0,                                                              0,                     -\alpha**2/(-36*\alpha**2 - 10*\alpha - 1),                                                              0,        (-8*\alpha**2 - \alpha)/(-36*\alpha**2 - 10*\alpha - 1)],
[                                                             0, (-28*\alpha**2 - 9*\alpha - 1)/(-36*\alpha**2 - 10*\alpha - 1),                                                              0,        (-8*\alpha**2 - \alpha)/(-36*\alpha**2 - 10*\alpha - 1),                                                              0,                     -\alpha*

In [25]:
# Define the symbols
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

# Create a 6x6 matrix based on the given pattern
C_mat = sym.Matrix(4,4, lambda i, j: C_R+C_C/2 if (i == j and np.mod(i,2)==0) else C_F+C_C/2 if (i == j and np.mod(i,2)!=0)  else -C_C/2 if abs(i-j) == 2 else 0)

C_mat

Matrix([
[C_C/2 + C_R,           0,      -C_C/2,           0],
[          0, C_C/2 + C_F,           0,      -C_C/2],
[     -C_C/2,           0, C_C/2 + C_R,           0],
[          0,      -C_C/2,           0, C_C/2 + C_F]])

In [26]:
C_inv = C_mat **-1

In [31]:
sym.simplify(C_inv)

Matrix([
[(C_C/2 + C_R)/(C_R*(C_C + C_R)),                               0,         C_C/(2*C_R*(C_C + C_R)),                               0],
[                              0, (C_C/2 + C_F)/(C_F*(C_C + C_F)),                               0,         C_C/(2*C_F*(C_C + C_F))],
[        C_C/(2*C_R*(C_C + C_R)),                               0, (C_C/2 + C_R)/(C_R*(C_C + C_R)),                               0],
[                              0,         C_C/(2*C_F*(C_C + C_F)),                               0, (C_C/2 + C_F)/(C_F*(C_C + C_F))]])

In [30]:
sym.print_latex(sym.simplify(C_inv))

\left[\begin{matrix}\frac{\frac{C_{C}}{2} + C_{R}}{C_{R} \left(C_{C} + C_{R}\right)} & 0 & \frac{C_{C}}{2 C_{R} \left(C_{C} + C_{R}\right)} & 0\\0 & \frac{\frac{C_{C}}{2} + C_{F}}{C_{F} \left(C_{C} + C_{F}\right)} & 0 & \frac{C_{C}}{2 C_{F} \left(C_{C} + C_{F}\right)}\\\frac{C_{C}}{2 C_{R} \left(C_{C} + C_{R}\right)} & 0 & \frac{\frac{C_{C}}{2} + C_{R}}{C_{R} \left(C_{C} + C_{R}\right)} & 0\\0 & \frac{C_{C}}{2 C_{F} \left(C_{C} + C_{F}\right)} & 0 & \frac{\frac{C_{C}}{2} + C_{F}}{C_{F} \left(C_{C} + C_{F}\right)}\end{matrix}\right]


In [18]:
# Define the symbols
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

# Create a 6x6 matrix based on the given pattern
C_mat = sym.Matrix(10,10, lambda i, j: C_R+C_C/2 if (i == j and np.mod(i,2)==0) else C_F+C_C/2 if (i == j and np.mod(i,2)!=0)  else -C_C/2 if abs(i-j) == 2 else 0)

C_mat

Matrix([
[C_C/2 + C_R,           0,      -C_C/2,           0,           0,           0,           0,           0,           0,           0],
[          0, C_C/2 + C_F,           0,      -C_C/2,           0,           0,           0,           0,           0,           0],
[     -C_C/2,           0, C_C/2 + C_R,           0,      -C_C/2,           0,           0,           0,           0,           0],
[          0,      -C_C/2,           0, C_C/2 + C_F,           0,      -C_C/2,           0,           0,           0,           0],
[          0,           0,      -C_C/2,           0, C_C/2 + C_R,           0,      -C_C/2,           0,           0,           0],
[          0,           0,           0,      -C_C/2,           0, C_C/2 + C_F,           0,      -C_C/2,           0,           0],
[          0,           0,           0,           0,      -C_C/2,           0, C_C/2 + C_R,           0,      -C_C/2,           0],
[          0,           0,           0,           0,           0,  

In [19]:
C_inv = C_mat **-1

In [20]:
sym.simplify(C_inv)

Matrix([
[(-C_C**4/4 - C_C**3*C_R + 3*C_C**2*C_R**2 + 8*C_C*C_R**3 + 4*C_R**4)/(C_R*(-C_C**4 - C_C**3*C_R + 6*C_C**2*C_R**2 + 10*C_C*C_R**3 + 4*C_R**4)),                                                                                                                                              0,                C_C*(-C_C**2 + 4*C_C*C_R + 4*C_R**2)/(4*C_R*(-C_C**3 + C_C**2*C_R + 4*C_C*C_R**2 + 2*C_R**3)),                                                                                                            0,            C_C**2/(-C_C**3 + 6*C_C*C_R**2 + 4*C_R**3),                                                     0,                                              C_C**3/(4*C_R*(-C_C**3 + C_C**2*C_R + 4*C_C*C_R**2 + 2*C_R**3)),                                                                                                            0,                                                             C_C**4/(4*C_R*(-C_C**4 - C_C**3*C_R + 6*C_C**2*C_R**2 + 10*C_C*C_R**3 + 4*C_R**4)),         