In [2]:
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt

In [3]:
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

In [4]:
C = sym.Matrix([[C_R+C_C, 0      , -C_C/4 , -C_C/4 ],
                [0      , C_F+C_C, -C_C/4 , -C_C/4 ],
                [-C_C/4 , -C_C/4 , C_R+C_C, 0      ],
                [-C_C/4 , -C_C/4 , 0      , C_F+C_C] ])

In [5]:
C_inv = C**-1

In [6]:
sym.simplify(C_inv)

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [7]:
sym.simplify(C_inv )

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [8]:
sym.factor(C_inv[0,0])

(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/((2*C_C**2 + 3*C_C*C_F + 3*C_C*C_R + 4*C_F*C_R)*(6*C_C**2 + 5*C_C*C_F + 5*C_C*C_R + 4*C_F*C_R))

In [9]:
C_inv[0,0] - C_inv[2,2]

0

In [10]:
Csh = 15
C   = 15
Cg  = 10
CJ  = 3
Cc  = 10

In [11]:
a=np.array( C_inv.subs({C_C:Cc, C_R:C/2, C_F:C/2 + Csh + CJ}).evalf() )

In [12]:
a/a[0,0]

array([[1.00000000000000, 0.0152487268751618, 0.145035532410737,
        0.0714963892165607],
       [0.0152487268751618, 0.485225997640763, 0.0714963892165607,
        0.0352446989095722],
       [0.145035532410737, 0.0714963892165607, 1.00000000000000,
        0.0152487268751618],
       [0.0714963892165607, 0.0352446989095722, 0.0152487268751618,
        0.485225997640763]], dtype=object)

In [13]:
C_R = C/2
C_C = Cc
C_F = C/2 + Csh + CJ
C   = np.array([  [C_R + C_C, 0, -C_C / 4, -C_C / 4],
                  [0, C_F + C_C, -C_C / 4, -C_C / 4],
                  [-C_C / 4, -C_C / 4, C_R + C_C, 0],
                  [-C_C / 4, -C_C / 4, 0, C_F + C_C]])

In [14]:
C

array([[17.5,  0. , -2.5, -2.5],
       [ 0. , 35.5, -2.5, -2.5],
       [-2.5, -2.5, 17.5,  0. ],
       [-2.5, -2.5,  0. , 35.5]])

In [20]:
np.linalg.inv(C)**-1

array([[  16.9586702 , 1112.13679245,  116.92769292,  237.19617706],
       [1112.13679245,   34.95004447,  237.19617706,  481.16938776],
       [ 116.92769292,  237.19617706,   16.9586702 , 1112.13679245],
       [ 237.19617706,  481.16938776, 1112.13679245,   34.95004447]])

In [23]:
C_F + C_C

35.5

In [24]:
C_R + C_C

17.5