In [2]:
import sympy as sym
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def neglect_terms(expr, N):
    # Function to neglect terms of order N and higher in a polynomial
    # Split the expression into numerator and denominator
    num, denom = expr.as_numer_denom()
    # Process numerator and denominator to remove terms of order N and higher
    num_neglected = sum(coeff * term for term, coeff in num.as_coefficients_dict().items() if all(pow < N for var, pow in term.as_powers_dict().items()))
    denom_neglected = sum(coeff * term for term, coeff in denom.as_coefficients_dict().items() if all(pow < N for var, pow in term.as_powers_dict().items()))
    # Reconstruct the fraction
    return num_neglected / denom_neglected

def neglect_terms_in_matrix(matrix, N):
    # Process each element in the matrix
    processed_matrix = matrix.applyfunc(lambda x: neglect_terms(x, N))

    return processed_matrix

In [4]:
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

In [5]:
C = sym.Matrix([[C_R+C_C, 0      , -C_C/4 , -C_C/4 ],
                [0      , C_F+C_C, -C_C/4 , -C_C/4 ],
                [-C_C/4 , -C_C/4 , C_R+C_C, 0      ],
                [-C_C/4 , -C_C/4 , 0      , C_F+C_C] ])

In [4]:
C_inv = C**-1

In [5]:
sym.simplify(C_inv)

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [6]:
sym.simplify(C_inv )

Matrix([
[(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                                   C_C**2*(2*C_C + C_F + C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                          4*C_C*(C_C**2 + 2*C_C*C_F + C_F**2)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_F*C_R**2 + 16*C_F**2*C_R**2),                                                 4*C_C*(C_C**2 + C_C*C_F + C_C*C_R + C_F*C_R)/(12*C_C**4 + 28*C_C**3*C_F + 28*C_C**3*C_R + 15*C_C**2*C_F**2 + 62*C_C**2*C_F*C_R + 15*C_C**2*C_R**2 + 32*C_C*C_F**2*C_R + 32*C_C*C_

In [7]:
sym.factor(C_inv[0,0])

(14*C_C**3 + 31*C_C**2*C_F + 15*C_C**2*C_R + 16*C_C*C_F**2 + 32*C_C*C_F*C_R + 16*C_F**2*C_R)/((2*C_C**2 + 3*C_C*C_F + 3*C_C*C_R + 4*C_F*C_R)*(6*C_C**2 + 5*C_C*C_F + 5*C_C*C_R + 4*C_F*C_R))

In [8]:
C_inv[0,0] - C_inv[2,2]

0

In [9]:
Csh = 15
C   = 15
Cg  = 10
CJ  = 3
Cc  = 10

In [10]:
a=np.array( C_inv.subs({C_C:Cc, C_R:C/2, C_F:C/2 + Csh + CJ}).evalf() )

In [11]:
a/a[0,0]

array([[1.00000000000000, 0.0152487268751618, 0.145035532410737,
        0.0714963892165607],
       [0.0152487268751618, 0.485225997640763, 0.0714963892165607,
        0.0352446989095722],
       [0.145035532410737, 0.0714963892165607, 1.00000000000000,
        0.0152487268751618],
       [0.0714963892165607, 0.0352446989095722, 0.0152487268751618,
        0.485225997640763]], dtype=object)

In [12]:
C_R = C/2
C_C = Cc
C_F = C/2 + Csh + CJ
C   = np.array([  [C_R + C_C, 0, -C_C / 4, -C_C / 4],
                  [0, C_F + C_C, -C_C / 4, -C_C / 4],
                  [-C_C / 4, -C_C / 4, C_R + C_C, 0],
                  [-C_C / 4, -C_C / 4, 0, C_F + C_C]])

In [13]:
C

array([[17.5,  0. , -2.5, -2.5],
       [ 0. , 35.5, -2.5, -2.5],
       [-2.5, -2.5, 17.5,  0. ],
       [-2.5, -2.5,  0. , 35.5]])

In [14]:
np.linalg.inv(C)**-1

array([[  16.9586702 , 1112.13679245,  116.92769292,  237.19617706],
       [1112.13679245,   34.95004447,  237.19617706,  481.16938776],
       [ 116.92769292,  237.19617706,   16.9586702 , 1112.13679245],
       [ 237.19617706,  481.16938776, 1112.13679245,   34.95004447]])

In [15]:
C_F + C_C

35.5

In [16]:
C_R + C_C

17.5

In [9]:
# Define the symbols
alpha= sym.symbols('\\alpha', real=True, positive = True, nonzero=True)
N=6
C_mat = sym.Matrix(N,N, lambda i, j: -1 if abs(i-j) == 2 else 0)
C_mat**2

Matrix([
[1, 0, 0, 0, 1, 0],
[0, 1, 0, 0, 0, 1],
[0, 0, 2, 0, 0, 0],
[0, 0, 0, 2, 0, 0],
[1, 0, 0, 0, 1, 0],
[0, 1, 0, 0, 0, 1]])

In [4]:
# Define the symbols
alpha= sym.symbols('\\alpha', real=True, positive = True, nonzero=True)
N=6
C_mat = sym.Matrix(N,N, lambda i, j: 1+alpha if i == j else -alpha if abs(i-j) == 2 else -alpha if ((i==N-1 and j==0) or (i==0 and j==N-1) )  else 0)
C_mat = sym.Matrix(N,N, lambda i, j: 1+alpha if i == j else -alpha if abs(i-j) == 2 else -alpha if abs(i-j) == 1 else -alpha if ((i==N-1 and j==0) or (i==0 and j==N-1) )  else 0)
# C_mat = sym.Matrix(N,N, lambda i, j: 1+alpha if i == j else -alpha if abs(i-j) == 2  else 0)

C_mat

Matrix([
[\alpha + 1,    -\alpha,    -\alpha,          0,          0,    -\alpha],
[   -\alpha, \alpha + 1,    -\alpha,    -\alpha,          0,          0],
[   -\alpha,    -\alpha, \alpha + 1,    -\alpha,    -\alpha,          0],
[         0,    -\alpha,    -\alpha, \alpha + 1,    -\alpha,    -\alpha],
[         0,          0,    -\alpha,    -\alpha, \alpha + 1,    -\alpha],
[   -\alpha,          0,          0,    -\alpha,    -\alpha, \alpha + 1]])

In [19]:
C_inv = C_mat **-1
# C_inv = sym.simplify(C_inv)

In [20]:
C_inv

Matrix([
[(7*\alpha**5 + 25*\alpha**4 + 17*\alpha**3 - 3*\alpha**2 - 5*\alpha - 1)/(5*\alpha**6 + 36*\alpha**5 + 60*\alpha**4 + 28*\alpha**3 - 5*\alpha**2 - 6*\alpha - 1),         (4*\alpha**5 + 2*\alpha**4 - 6*\alpha**3 - 5*\alpha**2 - \alpha)/(5*\alpha**6 + 36*\alpha**5 + 60*\alpha**4 + 28*\alpha**3 - 5*\alpha**2 - 6*\alpha - 1),           (\alpha**5 - 4*\alpha**4 - 8*\alpha**3 - 5*\alpha**2 - \alpha)/(5*\alpha**6 + 36*\alpha**5 + 60*\alpha**4 + 28*\alpha**3 - 5*\alpha**2 - 6*\alpha - 1),               (-4*\alpha**5 - 15*\alpha**4 - 13*\alpha**3 - 3*\alpha**2)/(5*\alpha**6 + 36*\alpha**5 + 60*\alpha**4 + 28*\alpha**3 - 5*\alpha**2 - 6*\alpha - 1),               (-6*\alpha**5 - 15*\alpha**4 - 10*\alpha**3 - 2*\alpha**2)/(5*\alpha**6 + 36*\alpha**5 + 60*\alpha**4 + 28*\alpha**3 - 5*\alpha**2 - 6*\alpha - 1),        (-3*\alpha**5 - 2*\alpha**4 - 4*\alpha**3 - 4*\alpha**2 - \alpha)/(5*\alpha**6 + 36*\alpha**5 + 60*\alpha**4 + 28*\alpha**3 - 5*\alpha**2 - 6*\alpha - 1)],
[        (4*\alph

In [21]:
neglect_terms_in_matrix(C_inv,2)

Matrix([
[(-5*\alpha - 1)/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),                               0,                               0,         -\alpha/(-6*\alpha - 1)],
[        -\alpha/(-6*\alpha - 1), (-5*\alpha - 1)/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),                               0,                               0],
[        -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1), (-5*\alpha - 1)/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),                               0],
[                              0,         -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1), (-5*\alpha - 1)/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1)],
[                              0,                               0,         -\alpha/(-6*\alpha - 1),         -\alpha/(-6*\alpha - 1), (-5*\alpha - 1)/(-6*\alpha - 1),         -\alpha/(-6*\alph

In [9]:
U_0   = sym.polys.orthopolys.chebyshevu_poly(0,   x=(alpha+1)/(2*alpha)).simplify()
U_N   = sym.polys.orthopolys.chebyshevu_poly(N,   x=(alpha+1)/(2*alpha)).simplify()
U_Np1 = sym.polys.orthopolys.chebyshevu_poly(N+1, x=(alpha+1)/(2*alpha)).simplify()
U_Np2 = sym.polys.orthopolys.chebyshevu_poly(N+2, x=(alpha+1)/(2*alpha)).simplify()

In [17]:
C_inv[0,0]

(-2*\alpha**4 + \alpha**3 + 7*\alpha**2 + 5*\alpha + 1)/(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1)

In [10]:
C_inv_diag = U_Np2**-1 * alpha ** -1 * U_0 * U_Np1
C_inv_diag.expand().simplify()

(\alpha**7 + 3*\alpha**6 - 9*\alpha**5 - 15*\alpha**4 + 5*\alpha**3 + 15*\alpha**2 + 7*\alpha + 1)/(6*\alpha**7 + 3*\alpha**6 - 24*\alpha**5 - 20*\alpha**4 + 14*\alpha**3 + 21*\alpha**2 + 8*\alpha + 1)

In [11]:
C_inv_sub_diag = U_Np2**-1 * alpha ** -1 * U_0 * U_N
C_inv_sub_diag.expand().simplify()

\alpha*(\alpha**6 - 2*\alpha**5 - 9*\alpha**4 + 10*\alpha**2 + 6*\alpha + 1)/(6*\alpha**7 + 3*\alpha**6 - 24*\alpha**5 - 20*\alpha**4 + 14*\alpha**3 + 21*\alpha**2 + 8*\alpha + 1)

In [6]:
# Define the symbols
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

# Create a 6x6 matrix based on the given pattern
C_mat = sym.Matrix(4,4, lambda i, j: C_R+C_C/2 if (i == j and np.mod(i,2)==0) else C_F+C_C/2 if (i == j and np.mod(i,2)!=0)  else -C_C/2 if abs(i-j) == 2 else 0)
C_mat[1,-1] *=-1
C_mat[-1,1] *=-1
C_mat

Matrix([
[C_C/2 + C_R,           0,      -C_C/2,           0],
[          0, C_C/2 + C_F,           0,       C_C/2],
[     -C_C/2,           0, C_C/2 + C_R,           0],
[          0,       C_C/2,           0, C_C/2 + C_F]])

In [7]:
C_inv = C_mat **-1

In [8]:
sym.simplify(C_inv)

Matrix([
[(C_C/2 + C_R)/(C_R*(C_C + C_R)),                               0,         C_C/(2*C_R*(C_C + C_R)),                               0],
[                              0, (C_C/2 + C_F)/(C_F*(C_C + C_F)),                               0,        -C_C/(2*C_F*(C_C + C_F))],
[        C_C/(2*C_R*(C_C + C_R)),                               0, (C_C/2 + C_R)/(C_R*(C_C + C_R)),                               0],
[                              0,        -C_C/(2*C_F*(C_C + C_F)),                               0, (C_C/2 + C_F)/(C_F*(C_C + C_F))]])

In [30]:
sym.print_latex(sym.simplify(C_inv))

\left[\begin{matrix}\frac{\frac{C_{C}}{2} + C_{R}}{C_{R} \left(C_{C} + C_{R}\right)} & 0 & \frac{C_{C}}{2 C_{R} \left(C_{C} + C_{R}\right)} & 0\\0 & \frac{\frac{C_{C}}{2} + C_{F}}{C_{F} \left(C_{C} + C_{F}\right)} & 0 & \frac{C_{C}}{2 C_{F} \left(C_{C} + C_{F}\right)}\\\frac{C_{C}}{2 C_{R} \left(C_{C} + C_{R}\right)} & 0 & \frac{\frac{C_{C}}{2} + C_{R}}{C_{R} \left(C_{C} + C_{R}\right)} & 0\\0 & \frac{C_{C}}{2 C_{F} \left(C_{C} + C_{F}\right)} & 0 & \frac{\frac{C_{C}}{2} + C_{F}}{C_{F} \left(C_{C} + C_{F}\right)}\end{matrix}\right]


In [18]:
# Define the symbols
C_R, C_F, C_C = sym.symbols('C_R, C_F, C_C', real=True, positive=True, nonzero=True)

# Create a 6x6 matrix based on the given pattern
C_mat = sym.Matrix(10,10, lambda i, j: C_R+C_C/2 if (i == j and np.mod(i,2)==0) else C_F+C_C/2 if (i == j and np.mod(i,2)!=0)  else -C_C/2 if abs(i-j) == 2 else 0)

C_mat

Matrix([
[C_C/2 + C_R,           0,      -C_C/2,           0,           0,           0,           0,           0,           0,           0],
[          0, C_C/2 + C_F,           0,      -C_C/2,           0,           0,           0,           0,           0,           0],
[     -C_C/2,           0, C_C/2 + C_R,           0,      -C_C/2,           0,           0,           0,           0,           0],
[          0,      -C_C/2,           0, C_C/2 + C_F,           0,      -C_C/2,           0,           0,           0,           0],
[          0,           0,      -C_C/2,           0, C_C/2 + C_R,           0,      -C_C/2,           0,           0,           0],
[          0,           0,           0,      -C_C/2,           0, C_C/2 + C_F,           0,      -C_C/2,           0,           0],
[          0,           0,           0,           0,      -C_C/2,           0, C_C/2 + C_R,           0,      -C_C/2,           0],
[          0,           0,           0,           0,           0,  

In [19]:
C_inv = C_mat **-1

In [20]:
sym.simplify(C_inv)

Matrix([
[(-C_C**4/4 - C_C**3*C_R + 3*C_C**2*C_R**2 + 8*C_C*C_R**3 + 4*C_R**4)/(C_R*(-C_C**4 - C_C**3*C_R + 6*C_C**2*C_R**2 + 10*C_C*C_R**3 + 4*C_R**4)),                                                                                                                                              0,                C_C*(-C_C**2 + 4*C_C*C_R + 4*C_R**2)/(4*C_R*(-C_C**3 + C_C**2*C_R + 4*C_C*C_R**2 + 2*C_R**3)),                                                                                                            0,            C_C**2/(-C_C**3 + 6*C_C*C_R**2 + 4*C_R**3),                                                     0,                                              C_C**3/(4*C_R*(-C_C**3 + C_C**2*C_R + 4*C_C*C_R**2 + 2*C_R**3)),                                                                                                            0,                                                             C_C**4/(4*C_R*(-C_C**4 - C_C**3*C_R + 6*C_C**2*C_R**2 + 10*C_C*C_R**3 + 4*C_R**4)),         